apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deploymentName }}
  labels:
    app: {{ .Values.frontend.name }}
    tier: {{ .Values.frontend.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
      tier: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
        tier: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          ports:
              - containerPort: {{ .Values.frontend.port }}
      restartPolicy: {{ .Values.frontend.restartPolicy }}